In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline
sns.set()

In [59]:
df = pd.read_json('stevens_jan_19.json')

In [60]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 768 entries, 2456 to 3223
Data columns (total 15 columns):
Date/Time (PST)             768 non-null object
Battery Voltage (v)         768 non-null float64
Temperature (deg F)         768 non-null float64
Wind Speed Minimum (mph)    768 non-null float64
Wind Speed Average (mph)    768 non-null float64
Wind Speed Maximum (mph)    768 non-null float64
Wind Direction (deg.)       768 non-null float64
date                        768 non-null datetime64[ns]
24 Hour Snow (in)           768 non-null float64
Total Snow Depth (in)       768 non-null float64
Relative Humidity (%)       0 non-null float64
area                        768 non-null object
danger_above_treeline       768 non-null int64
danger_below_treeline       768 non-null int64
danger_near_treeline        768 non-null int64
dtypes: datetime64[ns](1), float64(9), int64(3), object(2)
memory usage: 96.0+ KB

### It appears that for this month, there is no relative humidity

In [61]:
df.head()

,Date/Time (PST),Battery Voltage (v),Temperature (deg F),Wind Speed Minimum (mph),Wind Speed Average (mph),Wind Speed Maximum (mph),Wind Direction (deg.),date,24 Hour Snow (in),Total Snow Depth (in),Relative Humidity (%),area,danger_above_treeline,danger_below_treeline,danger_near_treeline
2456,2019-01-31 23:00:00,13.53,40.28,0.0,1.225,4.494,279.80,2019-01-31,0.448,86.5,NaN,Stevens Pass,1,1,1
2457,2019-01-31 22:00:00,12.58,39.91,0.0,3.626,6.905,108.30,2019-01-31,0.249,86.2,NaN,Stevens Pass,1,1,1
2458,2019-01-31 21:00:00,12.59,40.36,0.0,3.374,9.910,134.00,2019-01-31,0.387,86.5,NaN,Stevens Pass,1,1,1
2459,2019-01-31 20:00:00,12.60,40.50,0.0,2.754,12.710,53.62,2019-01-31,0.251,86.5,NaN,Stevens Pass,1,1,1
2460,2019-01-31 19:00:00,12.61,39.87,0.0,2.020,8.860,187.60,2019-01-31,0.389,86.5,NaN,Stevens Pass,1,1,1

In [62]:
df['Date/Time (PST)'] = pd.to_datetime(df['Date/Time (PST)'])

In [63]:
df.head(1)

,Date/Time (PST),Battery Voltage (v),Temperature (deg F),Wind Speed Minimum (mph),Wind Speed Average (mph),Wind Speed Maximum (mph),Wind Direction (deg.),date,24 Hour Snow (in),Total Snow Depth (in),Relative Humidity (%),area,danger_above_treeline,danger_below_treeline,danger_near_treeline
2456,2019-01-31 23:00:00,13.53,40.28,0.0,1.225,4.494,279.8,2019-01-31,0.448,86.5,NaN,Stevens Pass,1,1,1

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 768 entries, 2456 to 3223
Data columns (total 15 columns):
Date/Time (PST)             768 non-null datetime64[ns]
Battery Voltage (v)         768 non-null float64
Temperature (deg F)         768 non-null float64
Wind Speed Minimum (mph)    768 non-null float64
Wind Speed Average (mph)    768 non-null float64
Wind Speed Maximum (mph)    768 non-null float64
Wind Direction (deg.)       768 non-null float64
date                        768 non-null datetime64[ns]
24 Hour Snow (in)           768 non-null float64
Total Snow Depth (in)       768 non-null float64
Relative Humidity (%)       0 non-null float64
area                        768 non-null object
danger_above_treeline       768 non-null int64
danger_below_treeline       768 non-null int64
danger_near_treeline        768 non-null int64
dtypes: datetime64[ns](2), float64(9), int64(3), object(1)
memory usage: 96.0+ KB

In [100]:
df = df.drop('Relative Humidity (%)',axis=1)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 767 to 0
Data columns (total 19 columns):
index                       768 non-null int64
Date/Time (PST)             768 non-null datetime64[ns]
Battery Voltage (v)         768 non-null float64
Temperature (deg F)         768 non-null float64
Wind Speed Minimum (mph)    768 non-null float64
Wind Speed Average (mph)    768 non-null float64
Wind Speed Maximum (mph)    768 non-null float64
Wind Direction (deg.)       768 non-null float64
date                        768 non-null datetime64[ns]
24 Hour Snow (in)           768 non-null float64
Total Snow Depth (in)       768 non-null float64
area                        768 non-null object
danger_above_treeline       768 non-null int64
danger_below_treeline       768 non-null int64
danger_near_treeline        768 non-null int64
max_24_hour_temp            745 non-null float64
min_24_hour_temp            745 non-null float64
max_48_hour_temp            745 non-null float64
min_48_hour_temp            745 non-null float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(1)
memory usage: 114.1+ KB

In [101]:
df.describe()

,index,Battery Voltage (v),Temperature (deg F),Wind Speed Minimum (mph),Wind Speed Average (mph),Wind Speed Maximum (mph),Wind Direction (deg.),24 Hour Snow (in),Total Snow Depth (in),danger_above_treeline,danger_below_treeline,danger_near_treeline,max_24_hour_temp,min_24_hour_temp,max_48_hour_temp,min_48_hour_temp
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,745.000000,745.000000,745.000000,745.000000
mean,2839.500000,12.747096,27.758099,2.193491,6.345531,12.237727,180.079362,1.638430,83.524857,2.312500,1.718750,2.062500,31.871987,24.002953,31.871987,24.002953
std,221.846794,0.226518,6.491934,2.780953,4.162471,6.816254,93.162920,4.578625,7.632468,0.917027,0.760198,0.747878,6.093293,5.392280,6.093293,5.392280
min,2456.000000,12.530000,15.450000,0.000000,0.000000,0.000000,0.000000,0.071000,68.590000,1.000000,1.000000,1.000000,19.190000,15.450000,19.190000,15.450000
25%,2647.750000,12.610000,23.130000,0.000000,3.547250,8.062500,96.850000,0.341000,79.240000,2.000000,1.000000,1.750000,28.680000,20.100000,28.680000,20.100000
50%,2839.500000,12.680000,27.290000,1.085000,5.412500,11.030000,186.750000,0.459000,83.800000,2.000000,2.000000,2.000000,31.170000,23.930000,31.170000,23.930000
75%,3031.250000,12.790000,30.797500,3.595000,8.305000,14.585000,270.600000,1.259750,88.300000,3.000000,2.000000,3.000000,34.670000,26.840000,34.670000,26.840000
max,3223.000000,13.610000,46.230000,17.820000,26.230000,51.990000,334.100000,46.760000,204.500000,4.000000,3.000000,3.000000,46.230000,40.890000,46.230000,40.890000

In [65]:
df = df.reset_index()

In [66]:
df.head(3)

,index,Date/Time (PST),Battery Voltage (v),Temperature (deg F),Wind Speed Minimum (mph),Wind Speed Average (mph),Wind Speed Maximum (mph),Wind Direction (deg.),date,24 Hour Snow (in),Total Snow Depth (in),Relative Humidity (%),area,danger_above_treeline,danger_below_treeline,danger_near_treeline
0,2456,2019-01-31 23:00:00,13.53,40.28,0.0,1.225,4.494,279.8,2019-01-31,0.448,86.5,NaN,Stevens Pass,1,1,1
1,2457,2019-01-31 22:00:00,12.58,39.91,0.0,3.626,6.905,108.3,2019-01-31,0.249,86.2,NaN,Stevens Pass,1,1,1
2,2458,2019-01-31 21:00:00,12.59,40.36,0.0,3.374,9.910,134.0,2019-01-31,0.387,86.5,NaN,Stevens Pass,1,1,1

In [69]:
df = df.reindex(index=df.index[::-1])

In [70]:
df.head(10)

,index,Date/Time (PST),Battery Voltage (v),Temperature (deg F),Wind Speed Minimum (mph),Wind Speed Average (mph),Wind Speed Maximum (mph),Wind Direction (deg.),date,24 Hour Snow (in),Total Snow Depth (in),Relative Humidity (%),area,danger_above_treeline,danger_below_treeline,danger_near_treeline
767,3223,2019-01-01 00:00:00,12.56,22.31,1.688,5.976,14.45,235.4,2019-01-01,0.459,77.46,NaN,Stevens Pass,2,1,2
766,3222,2019-01-01 01:00:00,12.56,22.40,2.214,7.054,11.49,262.1,2019-01-01,0.459,77.73,NaN,Stevens Pass,2,1,2
765,3221,2019-01-01 02:00:00,12.55,21.19,1.644,9.110,14.71,270.7,2019-01-01,0.459,77.73,NaN,Stevens Pass,2,1,2
764,3220,2019-01-01 03:00:00,12.54,20.71,3.946,9.600,17.80,262.4,2019-01-01,0.392,77.73,NaN,Stevens Pass,2,1,2
763,3219,2019-01-01 04:00:00,13.51,21.48,2.872,10.020,21.13,258.7,2019-01-01,0.459,78.13,NaN,Stevens Pass,2,1,2
762,3218,2019-01-01 05:00:00,12.91,20.20,3.354,9.570,16.46,268.7,2019-01-01,0.459,78.06,NaN,Stevens Pass,2,1,2
761,3217,2019-01-01 06:00:00,12.79,22.04,6.335,10.480,16.37,272.2,2019-01-01,0.459,77.73,NaN,Stevens Pass,2,1,2
760,3216,2019-01-01 07:00:00,12.72,24.72,1.578,7.384,13.68,262.1,2019-01-01,0.459,78.26,NaN,Stevens Pass,2,1,2
759,3215,2019-01-01 08:00:00,12.67,25.85,4.121,10.660,17.10,270.6,2019-01-01,0.459,78.53,NaN,Stevens Pass,2,1,2
758,3214,2019-01-01 09:00:00,12.63,26.36,3.573,10.590,18.04,268.0,2019-01-01,0.329,77.60,NaN,Stevens Pass,2,1,2

In [71]:
df['max_24_hour_temp']= df['Temperature (deg F)'].rolling(24).max()
df['min_24_hour_temp']= df['Temperature (deg F)'].rolling(24).min()

In [73]:
df.head(48)

,index,Date/Time (PST),Battery Voltage (v),Temperature (deg F),Wind Speed Minimum (mph),Wind Speed Average (mph),Wind Speed Maximum (mph),Wind Direction (deg.),date,24 Hour Snow (in),Total Snow Depth (in),Relative Humidity (%),area,danger_above_treeline,danger_below_treeline,danger_near_treeline,max_24_hour_temp,min_24_hour_temp
767,3223,2019-01-01 00:00:00,12.56,22.31,1.688,5.976,14.450,235.4,2019-01-01,0.459,77.46,NaN,Stevens Pass,2,1,2,NaN,NaN
766,3222,2019-01-01 01:00:00,12.56,22.40,2.214,7.054,11.490,262.1,2019-01-01,0.459,77.73,NaN,Stevens Pass,2,1,2,NaN,NaN
765,3221,2019-01-01 02:00:00,12.55,21.19,1.644,9.110,14.710,270.7,2019-01-01,0.459,77.73,NaN,Stevens Pass,2,1,2,NaN,NaN
764,3220,2019-01-01 03:00:00,12.54,20.71,3.946,9.600,17.800,262.4,2019-01-01,0.392,77.73,NaN,Stevens Pass,2,1,2,NaN,NaN
763,3219,2019-01-01 04:00:00,13.51,21.48,2.872,10.020,21.130,258.7,2019-01-01,0.459,78.13,NaN,Stevens Pass,2,1,2,NaN,NaN
762,3218,2019-01-01 05:00:00,12.91,20.20,3.354,9.570,16.460,268.7,2019-01-01,0.459,78.06,NaN,Stevens Pass,2,1,2,NaN,NaN
761,3217,2019-01-01 06:00:00,12.79,22.04,6.335,10.480,16.370,272.2,2019-01-01,0.459,77.73,NaN,Stevens Pass,2,1,2,NaN,NaN
760,3216,2019-01-01 07:00:00,12.72,24.72,1.578,7.384,13.680,262.1,2019-01-01,0.459,78.26,NaN,Stevens Pass,2,1,2,NaN,NaN
759,3215,2019-01-01 08:00:00,12.67,25.85,4.121,10.660,17.100,270.6,2019-01-01,0.459,78.53,NaN,Stevens Pass,2,1,2,NaN,NaN
758,3214,2019-01-01 09:00:00,12.63,26.36,3.573,10.590,18.040,268.0,2019-01-01,0.329,77.60,NaN,Stevens Pass,2,1,2,NaN,NaN
757,3213,2019-01-01 10:00:00,12.61,24.75,5.173,11.060,15.690,264.8,2019-01-01,0.472,78.04,NaN,Stevens Pass,2,1,2,NaN,NaN
756,3212,2019-01-01 11:00:00,12.59,25.11,4.296,10.640,22.270,264.4,2019-01-01,0.459,77.86,NaN,Stevens Pass,2,1,2,NaN,NaN
755,3211,2019-01-01 12:00:00,12.57,25.36,8.420,15.400,25.360,264.8,2019-01-01,0.340,77.50,NaN,Stevens Pass,2,1,2,NaN,NaN
754,3210,2019-01-01 13:00:00,12.55,25.78,2.784,10.440,18.220,253.2,2019-01-01,0.341,77.17,NaN,Stevens Pass,2,1,2,NaN,NaN
753,3209,2019-01-01 14:00:00,12.55,25.71,4.779,10.110,18.610,253.5,2019-01-01,0.341,76.97,NaN,Stevens Pass,2,1,2,NaN,NaN
752,3208,2019-01-01 15:00:00,12.55,25.16,4.625,9.030,18.700,253.5,2019-01-01,0.341,76.70,NaN,Stevens Pass,2,1,2,NaN,NaN
751,3207,2019-01-01 16:00:00,12.54,26.33,3.617,8.170,13.940,260.3,2019-01-01,0.341,76.57,NaN,Stevens Pass,2,1,2,NaN,NaN
750,3206,2019-01-01 17:00:00,13.08,25.22,1.644,7.638,13.110,260.4,2019-01-01,0.341,76.30,NaN,Stevens Pass,2,1,2,NaN,NaN
749,3205,2019-01-01 18:00:00,12.84,27.37,0.899,6.873,13.090,253.4,2019-01-01,0.341,76.03,NaN,Stevens Pass,2,1,2,NaN,NaN
748,3204,2019-01-01 19:00:00,12.74,29.50,0.000,4.848,9.910,252.2,2019-01-01,0.475,75.49,NaN,Stevens Pass,2,1,2,NaN,NaN
747,3203,2019-01-01 20:00:00,12.68,29.55,0.789,3.744,10.700,259.0,2019-01-01,0.483,76.32,NaN,Stevens Pass,2,1,2,NaN,NaN
746,3202,2019-01-01 21:00:00,12.65,29.14,2.324,7.334,15.210,264.8,2019-01-01,0.350,75.72,NaN,Stevens Pass,2,1,2,NaN,NaN
745,3201,2019-01-01 22:00:00,12.61,30.53,0.153,4.671,8.790,251.4,2019-01-01,0.349,76.05,NaN,Stevens Pass,2,1,2,NaN,NaN
744,3200,2019-01-01 23:00:00,12.58,31.22,2.455,7.323,14.730,262.3,2019-01-01,0.281,75.52,NaN,Stevens Pass,2,1,2,31.22,20.20
743,3199,2019-01-02 00:00:00,12.57,31.89,0.351,3.956,9.230,188.4,2019-01-02,0.349,76.46,NaN,Stevens Pass,2,1,1,31.89,20.20
742,3198,2019-01-02 01:00:00,12.56,33.17,0.000,6.061,15.100,262.4,2019-01-02,0.484,75.79,NaN,Stevens Pass,2,1,1,33.17,20.20
741,3197,2019-01-02 02:00:00,12.55,30.18,4.406,10.410,18.350,259.5,2019-01-02,0.491,75.34,NaN,Stevens Pass,2,1,1,33.17,20.20
740,3196,2019-01-02 03:00:00,12.55,30.70,0.241,4.472,8.590,229.8,2019-01-02,0.282,75.38,NaN,Stevens Pass,2,1,1,33.17,20.20
739,3195,2019-01-02 04:00:00,12.55,33.90,0.000,4.990,10.300,235.4,2019-01-02,0.349,75.12,NaN,Stevens Pass,2,1,1,33.90,20.20
738,3194,2019-01-02 05:00:00,13.54,34.29,0.000,5.154,10.300,265.0,2019-01-02,0.357,75.67,NaN,Stevens Pass,2,1,1,34.29,22.04
737,3193,2019-01-02 06:00:00,13.04,32.31,0.000,3.825,7.519,278.7,2019-01-02,0.494,75.41,NaN,Stevens Pass,2,1,1,34.29,24.72
736,3192,2019-01-02 07:00:00,12.87,32.12,0.000,6.387,16.110,281.4,2019-01-02,0.498,75.43,NaN,Stevens Pass,2,1,1,34.29,24.75
735,3191,2019-01-02 08:00:00,12.82,31.72,0.000,4.048,11.160,276.8,2019-01-02,0.498,75.83,NaN,Stevens Pass,2,1,1,34.29,24.75
734,3190,2019-01-02 09:00:00,12.78,31.98,0.000,3.385,10.480,270.0,2019-01-02,0.499,204.50,NaN,Stevens Pass,2,1,1,34.29,24.75
733,3189,2019-01-02 10:00:00,12.74,32.38,0.000,3.715,8.920,283.6,2019-01-02,0.365,76.51,NaN,Stevens Pass,2,1,1,34.29,25.11
732,3188,2019-01-02 11:00:00,12.70,33.12,0.000,3.679,11.270,282.5,2019-01-02,0.365,75.70,NaN,Stevens Pass,2,1,1,34.29,25.16
731,3187,2019-01-02 12:00:00,12.67,33.15,0.000,3.928,9.620,268.3,2019-01-02,0.365,75.57,NaN,Stevens Pass,2,1,1,34.29,25.16
730,3186,2019-01-02 13:00:00,12.64,32.35,0.000,4.803,13.280,272.6,2019-01-02,0.366,75.97,NaN,Stevens Pass,2,1,1,34.29,25.16
729,3185,2019-01-02 14:00:00,12.62,31.21,0.000,3.858,14.030,275.8,2019-01-02,0.365,75.83,NaN,Stevens Pass,2,1,1,34.29,25.16
728,3184,2019-01-02 15:00:00,12.61,29.57,0.000,4.701,12.280,265.0,2019-01-02,0.222,75.67,NaN,Stevens Pass,2,1,1,34.29,25.22
727,3183,2019-01-02 16:00:00,12.56,28.43,0.000,2.854,10.280,271.9,2019-01-02,0.351,75.52,NaN,Stevens Pass,2,1,1,34.29,25.22
726,3182,2019-01-02 17:00:00,12.58,27.69,0.000,4.292,11.140,264.7,2019-01-02,0.349,75.65,NaN,Stevens Pass,2,1,1,34.29,27.37
725,3181,2019-01-02 18:00:00,13.56,28.30,0.066,5.758,12.250,267.7,2019-01-02,0.349,75.38,NaN,Stevens Pass,2,1,1,34.29,27.69
724,3180,2019-01-02 19:00:00,12.93,28.70,0.022,5.110,12.410,259.8,2019-01-02,0.350,76.19,NaN,Stevens Pass,2,1,1,34.29,27.69
723,3179,2019-01-02 20:00:00,12.83,30.65,0.219,6.699,14.600,269.3,2019-01-02,0.491,76.48,NaN,Stevens Pass,2,1,1,34.29,27.69
722,3178,2019-01-02 21:00:00,12.78,31.84,0.789,6.041,12.760,262.5,2019-01-02,0.499,76.10,NaN,Stevens Pass,2,1,1,34.29,27.69
721,3177,2019-01-02 22:00:00,12.74,32.72,0.088,4.949,13.830,268.7,2019-01-02,0.503,75.44,NaN,Stevens Pass,2,1,1,34.29,27.69
720,3176,2019-01-02 23:00:00,12.70,33.50,0.000,4.089,11.840,268.7,2019-01-02,0.238,75.19,NaN,Stevens Pass,2,1,1,34.29,27.69

In [74]:
df['max_48_hour_temp']= df['Temperature (deg F)'].rolling(24).max()
df['min_48_hour_temp']= df['Temperature (deg F)'].rolling(24).min()

In [79]:
df.iloc[[50]]

,index,Date/Time (PST),Battery Voltage (v),Temperature (deg F),Wind Speed Minimum (mph),Wind Speed Average (mph),Wind Speed Maximum (mph),Wind Direction (deg.),date,24 Hour Snow (in),Total Snow Depth (in),Relative Humidity (%),area,danger_above_treeline,danger_below_treeline,danger_near_treeline,max_24_hour_temp,min_24_hour_temp,max_48_hour_temp,min_48_hour_temp
717,3173,2019-01-03 02:00:00,12.63,35.31,0.0,3.245,10.76,271.2,2019-01-03,0.507,74.52,NaN,Stevens Pass,4,3,3,35.31,27.69,35.31,27.69

In [80]:
df.columns

Index(['index', 'Date/Time (PST)', 'Battery Voltage (v)',
       'Temperature (deg F)', 'Wind Speed Minimum (mph)',
       'Wind Speed Average (mph)', 'Wind Speed Maximum (mph)',
       'Wind Direction (deg.)', 'date', '24 Hour Snow (in)',
       'Total Snow Depth (in)', 'Relative Humidity (%)', 'area',
       'danger_above_treeline', 'danger_below_treeline',
       'danger_near_treeline', 'max_24_hour_temp', 'min_24_hour_temp',
       'max_48_hour_temp', 'min_48_hour_temp'],
      dtype='object')

## Now, what do i want my X's to be?? 

X: temp, wind speed average, 24 hour snow (in), max/min 24 and 48 H temp 

Y: danger_near_treeline

In [154]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn_pandas import DataFrameMapper, cross_val_score
from sklearn_pandas.pipeline import Pipeline
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import FunctionTransformer
from sklearn.metrics import mean_absolute_error, accuracy_score, mean_squared_error

In [117]:
df_no_na = df.dropna()

df_no_na.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 745 entries, 744 to 0
Data columns (total 19 columns):
index                       745 non-null int64
Date/Time (PST)             745 non-null datetime64[ns]
Battery Voltage (v)         745 non-null float64
Temperature (deg F)         745 non-null float64
Wind Speed Minimum (mph)    745 non-null float64
Wind Speed Average (mph)    745 non-null float64
Wind Speed Maximum (mph)    745 non-null float64
Wind Direction (deg.)       745 non-null float64
date                        745 non-null datetime64[ns]
24 Hour Snow (in)           745 non-null float64
Total Snow Depth (in)       745 non-null float64
area                        745 non-null object
danger_above_treeline       745 non-null int64
danger_below_treeline       745 non-null int64
danger_near_treeline        745 non-null int64
max_24_hour_temp            745 non-null float64
min_24_hour_temp            745 non-null float64
max_48_hour_temp            745 non-null float64
min_48_hour_temp            745 non-null float64
dtypes: datetime64[ns](2), float64(12), int64(4), object(1)
memory usage: 116.4+ KB

In [118]:
X = df_no_na[['Temperature (deg F)',
        'Wind Speed Average (mph)',
        '24 Hour Snow (in)',
        'Total Snow Depth (in)',
        'max_24_hour_temp', 'min_24_hour_temp',
        'max_48_hour_temp', 'min_48_hour_temp']]

In [119]:
y = df_no_na['danger_near_treeline']

In [120]:
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=10)

DO A CHRONOLIGCAL SPLIT, because its a time series problem

In [124]:
X_train.isna().sum()

Temperature (deg F)         0
Wind Speed Average (mph)    0
24 Hour Snow (in)           0
Total Snow Depth (in)       0
max_24_hour_temp            0
min_24_hour_temp            0
max_48_hour_temp            0
min_48_hour_temp            0
dtype: int64

In [125]:
ss = StandardScaler()

In [126]:
mapper = DataFrameMapper([
    (['Temperature (deg F)','Wind Speed Average (mph)','24 Hour Snow (in)','Total Snow Depth (in)',
        'max_24_hour_temp', 'min_24_hour_temp','max_48_hour_temp', 'min_48_hour_temp'], ss)
    ])

In [127]:
lr = LinearRegression()
rfr = RandomForestRegressor(n_estimators=100)
gbr = GradientBoostingRegressor(n_estimators=100)
knnr = KNeighborsRegressor()
regressors = [lr, rfr, gbr, knnr]

In [128]:
reg_names = ['LinearRegression',
             'RandomForestRegressor',
             'GradientBoostingRegressor',
             'KNeighborsRegressor'
            ]

In [160]:
baseline_pred = np.mean(y_train)
residuals = (y_test - baseline_pred)
median_absolute_error = np.median(np.abs(residuals))
rmse=np.sqrt(np.mean(residuals**2))

print(median_absolute_error,rmse)

0.9874551971326166 0.7312751837379953

In [162]:
print(f'The MAE of just predicting the mean'
          f' is: {median_absolute_error}\n'
          f'The RMSE just predicting the mean'
          f' is: {rmse}\n'
      '==================================================================\n'
          '========================\n')

for regressor,name in zip(regressors,reg_names): #zip returns a tuple for each pair it is given
    pipe = Pipeline(steps=[
        ('transform',mapper),
        ('regressor', regressor)
    ])
    pipe.fit(X_train, y_train)
    preds = pipe.predict(X_test)
    print(f'The MAE of the {name}'
          f' is: {mean_absolute_error((y_test),preds)}\n'
          f'The RMSE of the {name}'
          f' is: {mean_squared_error((y_test),preds)}\n'
          
          '==================================================================\n'
          '========================\n'
         )

The MAE of just predicting the mean is: 0.9874551971326166
The RMSE just predicting the mean is: 0.7312751837379953
==================================================================
========================

The MAE of the LinearRegression is: 0.5289269817225615
The RMSE of the LinearRegression is: 0.420072163345939
==================================================================
========================

The MAE of the RandomForestRegressor is: 0.10550802139037431
The RMSE of the RandomForestRegressor is: 0.060286096256684484
==================================================================
========================

The MAE of the GradientBoostingRegressor is: 0.17758375416708258
The RMSE of the GradientBoostingRegressor is: 0.07785220194458436
==================================================================
========================

The MAE of the KNeighborsRegressor is: 0.1272727272727273
The RMSE of the KNeighborsRegressor is: 0.06866310160427806
==================================================================
========================

In [143]:
y_test[0:20]

509    2
527    2
125    2
374    1
81     1
467    2
235    3
46     1
112    2
346    3
393    1
220    3
460    2
156    2
459    2
717    3
533    3
337    3
345    3
182    3
Name: danger_near_treeline, dtype: int64

In [142]:
pipe.predict(X_test)[0:20]

array([2. , 2.4, 2. , 1. , 1.8, 2. , 3. , 1. , 2. , 3. , 1. , 3. , 2. ,
       3. , 2. , 3. , 2.8, 3. , 2.8, 3. ])

## YAY! FIRST STINKY MODEL!

But boo, very shitty model, its okay, i need more data points